### ISSUE TITLE
Can't start program on Arch Linux

### ISSUE THREAD

**Issue by ftraxxler** [pdfarranger/pdfarranger#1082]
Describe the bug
----------------
I can't start the program on my Arch Linux system.

I get the following error immediatly after I start the Programm

```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 267, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 114, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 5, in <module>
    from pdfarranger.pdfarranger import main
  File "/usr/lib/python3.11/site-packages/pdfarranger/pdfarranger.py", line 98, in <module>
    from gi.repository import Gtk
  File "/usr/lib/python3.11/site-packages/gi/importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GObject', version '2.0' not found
```

Screenshots
-----------
![image](https://github.com/pdfarranger/pdfarranger/assets/31884866/df567250-b99e-4856-b608-6a4babedc4f0)

System and Versions
-------------------
pdfarranger-1.10.1-1
pikepdf 8.15.0
Arch Linux  6.6.25-1-lts
I have GTK4 GTK3 and GTK2 installed

**Comment by ftraxxler** [comment]
I think that was the issue. Although I didn't change anything and now it works
