### ISSUE TITLE
Setup instructions for Windows

### ISSUE THREAD

**Issue by StefRe** [pdfarranger/pdfarranger#1152]
Describe the bug
----------------

With Python 3.12, setting `SETUPTOOLS_USE_DISTUTILS=stdlib` as advised in [Win32.md](https://github.com/pdfarranger/pdfarranger/blob/main/Win32.md#prerequisites) results in an error `ModuleNotFoundError: No module named 'distutils'` from `msys64/tmp/pip-build-env-bhkcyj7t/overlay/lib/python3.12/site-packages/setuptools/monkey.py", line 13, in <module>` where it tries to `import distutils.filelist`.

To Reproduce
------------

1.  Fresh install MSYS2 (it currently installs Python 3.12) and follow the steps Prerequisites in [Win32.md](https://github.com/pdfarranger/pdfarranger/blob/main/Win32.md#prerequisites

<details>
  <summary>Full traceback </summary>

$ SETUPTOOLS_USE_DISTUTILS=stdlib  /mingw64/bin/python3.exe -m pip install --cert c:/einstellungen/bghde-CA.pem --user keyboard darkdetect pikepdf img2pdf
warning: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    $MINGW_PACKAGE_PREFIX-python-xyz', where xyz is the package you
    are trying to install.

    If you wish to install a non-MSYS2-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-MSYS2 packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have $MINGW_PACKAGE_PREFIX-python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python inst
allation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Collecting keyboard
  Using cached keyboard-0.13.5-py3-none-any.whl.metadata (4.0 kB)
Collecting darkdetect
  Using cached darkdetect-0.8.0-py3-none-any.whl.metadata (3.6 kB)
Collecting pikepdf
  Using cached pikepdf-9.4.2.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 231, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    super().__init__(
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 711, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:/programs/msys64/mingw64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/programs/msys64/mingw64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:/programs/msys64/tmp/pip-build-env-bhkcyj7t/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 24, in <module>
    from . import logging, monkey
  File "C:/programs/msys64/tmp/pip-build-env-bhkcyj7t/overlay/lib/python3.12/site-packages/setuptools/logging.py", line 5, in <module>
    from . import monkey
  File "C:/programs/msys64/tmp/pip-build-env-bhkcyj7t/overlay/lib/python3.12/site-packages/setuptools/monkey.py", line 13, in <module>
    import distutils.filelist
ModuleNotFoundError: No module named 'distutils'

</details>  

Expected behavior
-----------------

Install pikepdf and img2pdf with no error.

System and Versions
-------------------

-  Windows 10

**Comment by StefRe** [comment]
It installs without errors if I don't set `SETUPTOOLS_USE_DISTUTILS=stdlib`, but don't know enough of setuptools etc. to decide under what conditions the stdlib-workaround is necessary (maybe for Python < 3.12?).

**Comment by StefRe** [comment]
https://github.com/pypa/setuptools/issues/3625 appears to explain that `SETUPTOOLS_USE_DISTUTILS=stdlib` shouldn't be used with Python 3.12.
