### ISSUE TITLE
"Unsupported locale setting" on Fedora 33

### ISSUE THREAD

**Issue by ocosta** [pdfarranger/pdfarranger#347]
Installed from flathub on Fedora 33, and it won't even start:
```flatpak run com.github.jeromerobert.pdfarranger
Traceback (most recent call last):
  File "/app/bin/pdfarranger", line 11, in <module>
    load_entry_point('pdfarranger==1.6.2', 'console_scripts', 'pdfarranger')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 58, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
Locale is set to a mix of en_US and pt_BR:
```LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Please let me know if you need any additional info.

**Comment by dreua** [comment]
This is probably caused by this flatpak bug: https://github.com/flatpak/flatpak/issues/3514

Could you try the workaround: `flatpak update --subpath=pt org.gnome.Platform.Locale`?

**Comment by ocosta** [comment]
You nailed it: now it works =) Thanks!
