### ISSUE TITLE
Current arch release (community/pdfarranger) requires unavaliable version of pdfarranger module w/ Python 3.9

### ISSUE THREAD

**Issue by ihasdapie** [pdfarranger/pdfarranger#391]
Simple fix with changing  `__requires__ = 'pdfarranger==1.6.0'` to `__requires__ = 'pdfarranger>=1.6.0'` in executable file.
Probably a version mismatch when running on python3.9

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pdfarranger 1.6.2 (/usr/lib/python3.9/site-packages), Requirement.parse('pdfarranger==1.6.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ihasdapie/.local/bin/pdfarranger", line 33, in <module>
    sys.exit(load_entry_point('pdfarranger==1.6.0', 'console_scripts', 'pdfarranger')())
  File "/home/ihasdapie/.local/bin/pdfarranger", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 116, in <module>
    from . import exporter
  File "/usr/lib/python3.9/site-packages/pdfarranger/exporter.py", line 19, in <module>
    import pikepdf
  File "/usr/lib/python3.9/site-packages/pikepdf/__init__.py", line 21, in <module>
    from ._version import __version__
  File "/usr/lib/python3.9/site-packages/pikepdf/_version.py", line 7, in <module>
    from pkg_resources import DistributionNotFound
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pdfarranger==1.6.0' distribution was not found and is required by the application
```

**Comment by ihasdapie** [comment]
Actually looking again and checking the arch package it may very well just be me doing a messy upgrade.

**Comment by dreua** [comment]
> /home/ihasdapie/.local/bin/pdfarranger

this looks like you previously installed pdfarranger as user, probably via pip, while 

> /usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py

was installed as root, hopefully with the system package manager (since `sudo pip` is not recommended). Does that sound like a possible scenario?

Could you try fixing it by simply uninstalling via pip or removing the first file (that in `~/.local/bin`)?

**Comment by ihasdapie** [comment]
Yeah it had to do with the pip installed pdfarranger I had and the version installed through my package manager...I just had to be more careful after running -Syu for too long!
