### ISSUE TITLE
CLI-Argument: Properly handle file not found

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#486]
Describe the bug
----------------

Errors when opening files given as command line arguments are not catched and therefore the whole stack trace is printed. This can confuse both, users and automatic error reporting tools.

*Originally reported by Oliver Sampson in the [Fedora Bugtracker](https://bugzilla.redhat.com/show_bug.cgi?id=1957262)*

To Reproduce
------------

1. Go to CLI
2. Run something like: `pdfarranger this is not a file`

Expected behavior
-----------------

End user readable error message.

Screenshots
-----------
```
$ pdfarranger this is not a file
Traceback (most recent call last):
  File "/home/da/.local/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 273, in do_open
    a.addpages(f.get_path())
  File "/home/da/.local/lib/python3.9/site-packages/pdfarranger/core.py", line 343, in addpages
    pdfdoc = PDFDoc(filename, basename, self.app.tmp_dir, self.app.window)
  File "/home/da/.local/lib/python3.9/site-packages/pdfarranger/core.py", line 253, in __init__
    self.mtime = os.path.getmtime(filename)
  File "/usr/lib64/python3.9/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/da/this'
```

System and Versions
-------------------

-   PDF Arranger 1.7.1
-   OS name and version: Fedora 34

**Comment by dreua** [comment]
Thank you!
