### ISSUE TITLE
Error: only pages can be inserted

### ISSUE THREAD

**Issue by milegrin** [pdfarranger/pdfarranger#528]
Description:
Open an existing PDF by importing or cut&paste into pdfarranger and then proceeding to add or remove pages or any other other changes and when I try to save I get the error "only pages can be inserted"

OS: Ubuntu 2104 64
Hardware : HP i7 laptop
Version : pdfarranger 1.6.2

Steps tried to fix the issue :
- remove pdfarranger and all dependencies using "apt remove --purge"
- Re-install PDFArranger & dependencies
- Issue remains

PDFArranger was working upto about 4-5 weeks ago when I last used it, I suspect the last update may have broken something.

```
mg@peanut:~/Documents/airplane-kit_build/build_manual$ pdfarranger build_manual_with_rfs_notes.pdf
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 827, in _getiter
    aiter = self.get_iter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 871, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '123'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 606, in update_thumbnail
    row = self.model[num]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 846, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 829, in _getiter
    raise IndexError("could not find tree path '%s'" % key)
IndexError: could not find tree path '123'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 748, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 210, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 796, in save
    exporter.export(self.pdfqueue, to_export, file_out, m)
  File "/usr/lib/python3/dist-packages/pdfarranger/exporter.py", line 78, in export
    pdf_output.pages.append(new_page)
TypeError: only pages can be inserted
mg@peanut:~/Documents/airplane-kit_build/build_manual$

```

**Comment by jeromerobert** [comment]
And seven of them ! We should organize a party when we will reach 10 :-)

See https://github.com/pdfarranger/pdfarranger/issues?q=only+pages+can+be+inserted
