### ISSUE TITLE
ModuleNotFoundError: No module named 'DistUtilsExtra'

### ISSUE THREAD

**Issue by hongyi-zhao** [pdfarranger/pdfarranger#604]
On Ubuntu 20.04.3 LTS, I install `pdfarranger` according to the guidance [here](https://github.com/pdfarranger/pdfarranger#for-developers) using the following steps:

```
$ git clone https://github.com/pdfarranger/pdfarranger.git
$ pyenv shell datasci
$ python --version
Python 3.9.1
$ cd pdfarranger
$ ./setup.py build
Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/pdfarranger/pdfarranger.git/./setup.py", line 24, in <module>
    from DistUtilsExtra.command import (
ModuleNotFoundError: No module named 'DistUtilsExtra'
```
Then I try the following but still failed:
```
$ pip install distutils-extra
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement distutils-extra (from versions: none)
ERROR: No matching distribution found for distutils-extra
```
Any hints for fixing this problem? See [here](https://discuss.python.org/t/modulenotfounderror-no-module-named-distutilsextra/12834) for the relevant discussion.

Regards,
HZ

**Comment by kbengs** [comment]
Did you run this line?
```
sudo apt-get install python3-pip python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools
```

You maybe don't need all of those but at least python3-distutils-extra

**Comment by hongyi-zhao** [comment]
Yep, as shown below:
```
$ for i in python3-pip python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools; do dpkg --get-selections $i; done
python3-pip					install
python3-distutils-extra				install
python3-wheel					install
python3-gi					install
python3-gi-cairo				install
gir1.2-gtk-3.0:amd64				install
gir1.2-poppler-0.18:amd64			install
python3-setuptools				install
```

**Comment by dreua** [comment]
I'm assuming the pyenv command creates an empty environment for you. I'm not familiar with this so I can't help you any further unfortunately. I guess you'll have to find a way to install / display the system package inside the pyenv. Let us know if you find a solution.

**Comment by hongyi-zhao** [comment]
> I guess you'll have to find a way to install / display the system package inside the pyenv. Let us know if you find a solution.

See the following:

```
$ pyenv shell 3.8.3
$ pyenv virtualenv --system-site-packages pdfarranger
$ pyenv shell pdfarranger 
$ pip install -U pip
$ ./setup.py build
Traceback (most recent call last):
  File "./setup.py", line 24, in <module>
    from DistUtilsExtra.command import (
ModuleNotFoundError: No module named 'DistUtilsExtra'

$ pip list 
Package    Version
---------- ------------
pip        21.3.1
pyfiglet   0.8.post1
setuptools 41.2.0
vtk        9.0.20200612
```

**Comment by hongyi-zhao** [comment]
According to the notes [here](http://absolutearea.blogspot.com/2016/11/), I finally found the reason and found the following installation method:
```
$ git clone https://github.com/pdfarranger/pdfarranger.git pdfarranger.git 
$ cd pdfarranger.git 
$ pyenv shell 3.8.3
$ pyenv virtualenv --system-site-packages pdfarranger
$ pyenv shell pdfarranger 
$ pip install -U pip
# http://absolutearea.blogspot.com/2016/11/
$ pip install https://launchpad.net/python-distutils-extra/trunk/2.39/+download/python-distutils-extra-2.39.tar.gz
$ pip install img2pdf pygobject
$ pip install -e .
```
Now, `pdfarranger` can be used to directly open image files as below:
```
$ pdfarranger Selection_079.png 

(pdfarranger:18833): Gtk-WARNING **: 21:12:27.631: actionhelper: action win.export-selection can't be activated due to parameter type mismatch (parameter type i, target type NULL)
Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/pdfarranger/pdfarranger.git/pdfarranger/pdfarranger.py", line 586, in do_activate
    self.__create_actions()
  File "/home/werner/Public/repo/github.com/pdfarranger/pdfarranger.git/pdfarranger/pdfarranger.py", line 355, in __create_actions
    self.window.add_action(Gio.PropertyAction.new("main-menu", main_menu, "active"))
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/pdfarranger/pdfarranger.git/pdfarranger/pdfarranger.py", line 2122, in __update_num_pages
    self.uiXML.get_object("num_pages").set_text(str(num_pages))
AttributeError: 'NoneType' object has no attribute 'set_text'
Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/pdfarranger/pdfarranger.git/pdfarranger/pdfarranger.py", line 652, in render
    ctxt_id = self.status_bar2.get_context_id("rendering")
AttributeError: 'NoneType' object has no attribute 'get_context_id'
Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/pdfarranger/pdfarranger.git/pdfarranger/pdfarranger.py", line 765, in update_thumbnail
    ctxt_id = self.status_bar2.get_context_id("rendering")
AttributeError: 'NoneType' object has no attribute 'get_context_id'
```

![image](https://user-images.githubusercontent.com/11155854/147876997-b10cebcb-31af-4403-aa59-413a1757dca5.png)

But as you can see, there are still some error messages shown on the console.

Regards,
HZ

**Comment by jeromerobert** [comment]
`pip install -e` never worked with PDF Arranger, you must remove the `-e`.

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out. It really does the trick.

The other thing I still want to know is, why can't `python-distutils-extra` or `python3-distutils-extra` be installed as follows:
```
$ pip install python-distutils-extra
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement python-distutils-extra (from versions: none)
ERROR: No matching distribution found for python-distutils-extra
$ pip install python3-distutils-extra
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement python3-distutils-extra (from versions: none)
ERROR: No matching distribution found for python3-distutils-extra

```

**Comment by dreua** [comment]
I guess distutils-extra is simply not on pypi therefore pip can't fetch it. It looks like the PDF arranger related issues are resolved therefore I'll close this issue

**Comment by hongyi-zhao** [comment]
> I guess distutils-extra is simply not on pypi therefore pip can't fetch it.

I found its Git repository using the following method:
```
$ for i in python-distutils-extra python3-distutils-extra; do apt showsrc $i |& grep git; done | sort -u
Vcs-Git: https://salsa.debian.org/python-team/modules/python-distutils-extra.git
```
Therefore, for developers, the more robust and reasonable `pdfarranger` installation steps should be as follows:
```
$ sudo apt install gir1.2-gtk-3.0 gir1.2-poppler-0.18 
$ git clone https://github.com/pdfarranger/pdfarranger.git pdfarranger.git 
$ cd pdfarranger.git 
$ pyenv shell 3.8.3
$ pyenv virtualenv --system-site-packages pdfarranger
$ pyenv shell pdfarranger 
$ pip install -U pip
$ pip install git+https://salsa.debian.org/python-team/modules/python-distutils-extra.git
$ pip install img2pdf pygobject
$ pip install .
```

**Comment by jeromerobert** [comment]
> Therefore, for developers, the more robust and reasonable pdfarranger installation steps should be as follows:

No, no, definitly not. The robust way is the one described in the README.

pygobject and distutils-extra have non-python dependencies which are not in PyPI so they must not be installed the way you do. Or at least cannot be installed in a robust way, with only the step you describes.

If you want to find a "robust" way you must find why `--system-site-packages` does not allow to get the system `distutils-extra` in your virtualenv. It should, it does for us.

**Comment by hongyi-zhao** [comment]
> If you want to find a "robust" way you must find why `--system-site-packages` does not allow to get the system `distutils-extra` in your virtualenv.

If I use the `virtualenv` installed by apt and the `--system-site-packages` option to directly create a python virtual environment, the system packages will be seen by this virtual environment automatically. As for `pyenv` is used, the same effect can be achieved by the following steps:
```
$ pyenv shell system
$ pyenv virtualenv --system-site-packages test
$ pyenv shell test
$ pip list
Package                Version             
---------------------- --------------------
2ping                  4.3                 
acme                   1.1.0               
appdirs                1.4.3               
apturl                 0.5.2               
argcomplete            1.8.1               
atomicwrites           1.1.5               
attrs                  19.3.0              
backcall               0.1.0               
bcrypt                 3.1.7               
beautifulsoup4         4.8.2               
blinker                1.4                 
Brlapi                 0.7.0               
Brotli                 1.0.7               
certbot                0.40.0              
certifi                2019.11.28          
chardet                3.0.4               
chrome-gnome-shell     0.0.0               
Click                  7.0                 
colorama               0.4.3               
command-not-found      0.3                 
ConfigArgParse         0.13.0              
configobj              5.0.6               
crudini                0.9.3               
cryptography           2.8                 
cupshelpers            1.0                 
cycler                 0.10.0              
dbus-python            1.2.16              
decorator              4.4.2               
defer                  1.0.6               
devscripts             2.20.2ubuntu2       
distlib                0.3.0               
distro                 1.4.0               
distro-info            0.23ubuntu1         
duplicity              0.8.12.0            
entrypoints            0.3                 
fasteners              0.14.1              
filelock               3.0.12              
future                 0.18.2              
gpg                    1.13.1-unknown      
gssapi                 1.6.1               
html5lib               1.0.1               
httplib2               0.14.0              
humanize               1.0.0               
idna                   2.8                 
ifaddr                 0.1.6               
img2pdf                0.3.3               
importlib-metadata     1.5.0               
iniparse               0.4                 
ipython                7.13.0              
ipython-genutils       0.2.0               
jedi                   0.15.2              
josepy                 1.2.0               
keyring                18.0.1              
kiwisolver             1.0.1               
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
lockfile               0.12.2              
louis                  3.12.0              
lxml                   4.5.0               
lz4                    3.0.2+dfsg          
macaroonbakery         1.3.1               
Mako                   1.1.0               
Markdown               3.1.1               
MarkupSafe             1.1.0               
matplotlib             3.1.2               
meson                  0.53.2              
mock                   3.0.5               
monotonic              1.5                 
more-itertools         4.2.0               
mpmath                 1.1.0               
netifaces              0.10.4              
nose                   1.3.7               
numpy                  1.17.4              
oauthlib               3.1.0               
olefile                0.46                
packaging              20.3                
paramiko               2.6.0               
parsedatetime          2.4                 
parso                  0.5.2               
pbr                    5.4.5               
pdfarranger            1.4.2               
periodictable          1.5.2               
pexpect                4.6.0               
pickleshare            0.7.5               
pikepdf                1.10.3+dfsg         
Pillow                 7.0.0               
Pint                   0.10.1              
pip                    20.0.2              
pkg-resources          0.0.0               
pluggy                 0.13.0              
ply                    3.11                
prompt-toolkit         2.0.10              
protobuf               3.6.1               
py                     1.8.1               
py-cpuinfo             5.0.0               
py3dns                 3.2.1               
pycairo                1.16.2              
pycups                 1.9.73              
pycurl                 7.43.0.2            
pydantic               1.2                 
pyfiglet               0.8.post1           
Pygments               2.3.1               
PyGObject              3.36.0              
PyICU                  2.4.2               
PyJWT                  1.7.1               
pykerberos             1.1.14              
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
PyOpenGL               3.1.0               
pyOpenSSL              19.0.0              
pyparsing              2.4.6               
pyRFC3339              1.1                 
pytest                 4.6.9               
python-apt             2.0.0+ubuntu0.20.4.6
python-dateutil        2.7.3               
python-debian          0.1.36ubuntu1       
python-distutils-extra 2.39                
python-lzo             1.12                
python-magic           0.4.16              
pytz                   2019.3              
pyxattr                0.6.1               
pyxdg                  0.26                
PyYAML                 5.3.1               
qcelemental            0.5.0               
rencode                1.0.6               
reportlab              3.5.34              
requests               2.22.0              
requests-toolbelt      0.8.0               
requests-unixsocket    0.2.0               
scipy                  1.3.3               
SecretStorage          2.3.1               
setproctitle           1.1.10              
setuptools             44.0.0              
simplejson             3.16.0              
six                    1.14.0              
soupsieve              1.9.5               
ssh-import-id          5.10                
supervisor             4.1.0               
sympy                  1.5.1               
systemd-python         234                 
traitlets              4.3.3               
ubuntu-advantage-tools 20.3                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unidiff                0.5.5               
uritools               3.0.0               
urllib3                1.25.8              
usb-creator            0.3.7               
virtualenv             20.0.17             
wadllib                1.3.3               
wcwidth                0.1.8               
webencodings           0.5.1               
wheel                  0.34.2              
xkit                   0.0.0               
xpra                   3.0.6               
youtube-dl             2020.3.24           
zeroconf               0.24.4              
zipp                   1.0.0               
zope.component         4.3.0               
zope.event             4.4                 
zope.hookable          5.0.0               
zope.interface         4.7.1     
```

**Comment by dreua** [comment]
> I think `pip` is better than `setup.py`, just as the comments and suggestions [here](https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install).

Agreed, I created a PR to fix this. (Let's discuss anything related to pip vs setup.py in #605 ) 
The rest of our instructions are fine and should stay as is imo. Not everyone wants the added complexity of a venv and for PDF Arranger it is not really necessary.

**Comment by jeromerobert** [comment]
> I think pip is better than setup.py, just as the comments and suggestions here.

By "for developers" I mean that you can edit `.py` files and run in place without any additionnable actions. Here `./setup.py` is user to build the `.po` files, nothing else. I think what you want to do is installing from source, not develop, so you should use the *Install from source* section, which actually use `pip install`.

**Comment by hongyi-zhao** [comment]
> By "for developers" I mean that you can edit `.py` files and run in place without any additionnable actions. 

But this seems even more inconvenient.

> Here `./setup.py` is used to build the `.po` files, nothing else.

I'm not so familiar with the `.po` files. Are these files indispensable for running `pdfarranger` in place?

**Comment by dreua** [comment]
Alright I think this is a matter of taste, for me setup.py is a no go because I really want the option to uninstall cleanly (important if you want to test different versions / packages). I rather pip install after each change or develop without the translations. (I managed to setup my Pycharm to run PDF Arranger without installation somehow.)

Ideally `pip -e` would support both use cases without the other's downside but I believe it doesn't work with PDF Arranger for some reason. For now I'd say we leave the instructions as is.

**Comment by jeromerobert** [comment]
Yes `./setup.py install ` is no go because:

- It does not support uninstall
- But more because, it does not install PDF Arranger properly

Use `./setup.py build` or `pip install` but not `./setup.py install`. See #90.

**Comment by hongyi-zhao** [comment]
> (I managed to setup my Pycharm to run PDF Arranger without installation somehow.)

On my machine, I use Emacs and [wingide](https://wingware.com/).  Can you tell me the details of your setup steps for reference?

> Edit found the reason: #420

I've read through it but still can't figure out why pip will have this problem. I think pip is a modern, full-featured Python package installer, all edge cases  have been pre-considered and can be handled correctly.

**Comment by hongyi-zhao** [comment]
> Use `./setup.py build` or `pip install` but not `./setup.py install`. See #90.

But I think  `./setup.py build` only builds the package in place without installing it.

**Comment by dreua** [comment]
@jeromerobert alright, sorry I confused ./setup.py install and build. Thanks for the clarification!

**Comment by hongyi-zhao** [comment]
I have now confirmed the method described for the [developer](https://github.com/pdfarranger/pdfarranger#for-developers):

```
$ apt-file search -x /usr/bin/python$
python-is-python2: /usr/bin/python        
python-is-python3: /usr/bin/python
$ sudo apt install python-is-python3

$ ./setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/pdfarranger
copying pdfarranger/__init__.py -> build/lib/pdfarranger
copying pdfarranger/metadata.py -> build/lib/pdfarranger
copying pdfarranger/core.py -> build/lib/pdfarranger
copying pdfarranger/exporter.py -> build/lib/pdfarranger
copying pdfarranger/pdfarranger.py -> build/lib/pdfarranger
copying pdfarranger/splitter.py -> build/lib/pdfarranger
copying pdfarranger/undo.py -> build/lib/pdfarranger
copying pdfarranger/croputils.py -> build/lib/pdfarranger
copying pdfarranger/config.py -> build/lib/pdfarranger
copying pdfarranger/__main__.py -> build/lib/pdfarranger
copying pdfarranger/iconview.py -> build/lib/pdfarranger
running build_i18n
intltool-update -p -g pdfarranger
msgfmt po/de.po -o build/mo/de/LC_MESSAGES/pdfarranger.mo
msgfmt po/zh_CN.po -o build/mo/zh_CN/LC_MESSAGES/pdfarranger.mo
msgfmt po/zh_TW.po -o build/mo/zh_TW/LC_MESSAGES/pdfarranger.mo
msgfmt po/ca.po -o build/mo/ca/LC_MESSAGES/pdfarranger.mo
msgfmt po/sv.po -o build/mo/sv/LC_MESSAGES/pdfarranger.mo
msgfmt po/ko.po -o build/mo/ko/LC_MESSAGES/pdfarranger.mo
msgfmt po/pt_PT.po -o build/mo/pt_PT/LC_MESSAGES/pdfarranger.mo
msgfmt po/is.po -o build/mo/is/LC_MESSAGES/pdfarranger.mo
msgfmt po/ca@valencia.po -o build/mo/ca@valencia/LC_MESSAGES/pdfarranger.mo
msgfmt po/cs.po -o build/mo/cs/LC_MESSAGES/pdfarranger.mo
msgfmt po/pt_BR.po -o build/mo/pt_BR/LC_MESSAGES/pdfarranger.mo
msgfmt po/el.po -o build/mo/el/LC_MESSAGES/pdfarranger.mo
msgfmt po/fr.po -o build/mo/fr/LC_MESSAGES/pdfarranger.mo
msgfmt po/tr.po -o build/mo/tr/LC_MESSAGES/pdfarranger.mo
msgfmt po/es.po -o build/mo/es/LC_MESSAGES/pdfarranger.mo
msgfmt po/hr.po -o build/mo/hr/LC_MESSAGES/pdfarranger.mo
msgfmt po/pl_PL.po -o build/mo/pl_PL/LC_MESSAGES/pdfarranger.mo
msgfmt po/fi.po -o build/mo/fi/LC_MESSAGES/pdfarranger.mo
msgfmt po/ja.po -o build/mo/ja/LC_MESSAGES/pdfarranger.mo
msgfmt po/it.po -o build/mo/it/LC_MESSAGES/pdfarranger.mo
msgfmt po/hu.po -o build/mo/hu/LC_MESSAGES/pdfarranger.mo
msgfmt po/nl.po -o build/mo/nl/LC_MESSAGES/pdfarranger.mo
msgfmt po/id.po -o build/mo/id/LC_MESSAGES/pdfarranger.mo
msgfmt po/ru.po -o build/mo/ru/LC_MESSAGES/pdfarranger.mo
running build_icons
$ python -m pdfarranger 
``` 
In this method, the `python -m pdfarranger` must be run from the `pdfarranger` repository's top level root directory.
See [here](https://github.com/mviereck/x11docker/issues/401#issuecomment-1001021281) for relevant discussion.
