### ISSUE TITLE
ValueError while parsing metadata

### ISSUE THREAD

**Issue by Cimbali** [pdfarranger/pdfarranger#626]
Describe the bug
----------------

When trying to save a (potentially modified) PDF downloaded from sciencedirect.com (i.e. Elsevier), the metadata parser tries to split the following value as a qname:

```
d2UUdywiNodz.zd-Gn.iKncNNndz-lt6Sy9-Gnt3.m92MmgiSnMyJo9ePndmPmMyNmteTma
```

The uncaught ValueError this causes prevents the file from being correctly saved. The error comes from the unhandled format of this metadata value, which is expected to contain `:`. This is happening while merging metadata values. The full traceback is:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 976, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/usr/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 160, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 1044, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "/usr/lib/python3.8/site-packages/pdfarranger/metadata.py", line 85, in merge
    for k, v in meta.items():
  File "/usr/lib64/python3.8/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/usr/lib64/python3.8/site-packages/pikepdf/models/metadata.py", line 288, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/pikepdf/models/metadata.py", line 660, in __getitem__
    return next(self._get_element_values(key))
  File "/usr/lib64/python3.8/site-packages/pikepdf/models/metadata.py", line 651, in _get_element_values
    yield from (v[2] for v in self._get_elements(name))
  File "/usr/lib64/python3.8/site-packages/pikepdf/models/metadata.py", line 651, in <genexpr>
    yield from (v[2] for v in self._get_elements(name))
  File "/usr/lib64/python3.8/site-packages/pikepdf/models/metadata.py", line 633, in _get_elements
    qname = self._qname(name)
  File "/usr/lib64/python3.8/site-packages/pikepdf/models/metadata.py", line 565, in _qname
    prefix, tag = name.split(':', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

This is triggered while merging metadata

To Reproduce
------------

1. Open [`Chapter-10---Forward-Seismic-Simulation_2012_Structured-Parallel-Programming.pdf` (attached)][1]
2. Attempt saving

Expected behavior
-----------------

If the bug is due to incorrect metadata, the error should be caught and the offending metadata entry ignored. There already is handling for such an error but it seems insufficient as an (uncaught) error is raised instead of returning `None` as in #84.

If something else causes the error (e.g. incorrectly obtaining that metadata entry maybe?) that should be fixed instead.

Input files
-----------

File is attached. It is downloaded as-is from sciencedirect.com, unchanged:

[Chapter-10---Forward-Seismic-Simulation_2012_Structured-Parallel-Programming.pdf][1]

Screenshots
-----------

System and Versions
-------------------

- PDF Arranger v1.8.1
- pikepdf 2.12.2-2.1
- both installed as `rpm` via official OpenSUSE repos
- OpenSUSE Tumbleweed (version ID 20220116, i.e. reasonably up-to-date)

[1]: https://github.com/pdfarranger/pdfarranger/files/7971280/Chapter-10---Forward-Seismic-Simulation_2012_Structured-Parallel-Programming.pdf

**Comment by Cimbali** [comment]
For what it’s worth, here’s a quick & dirty patch of the workaround I used:

```
--- /usr/lib/python3.8/site-packages/pdfarranger/metadata.py    2021-12-10 10:58:34.000000000 +0100
+++ /usr/lib/python3.8/site-packages/pdfarranger/metadata.py    2022-01-31 15:11:55.826387636 +0100
@@ -75,4 +75,14 @@
         traceback.print_exc()
 
+def _safeiter(elements):
+    it = iter(elements)
+    while True:
+        try:
+            yield next(it)
+        except StopIteration:
+            break
+        except ValueError:
+            continue # traceback.print_exc()
+
 def merge(metadata, input_files):
     """ Merge current global metadata and each imported files meta data """
@@ -82,5 +92,5 @@
         with doc.open_metadata() as meta:
             load_from_docinfo(meta, doc)
-            for k, v in meta.items():
+            for k, v in _safeiter(meta.items()):
                 if not _pikepdf_meta_is_valid(v):
                     # workaround for https://github.com/pikepdf/pikepdf/issues/84
```
