### ISSUE TITLE
NotImplementedError: cannot save document

### ISSUE THREAD

**Issue by petaflot** [pdfarranger/pdfarranger#768]
Describe the bug
----------------
attempting to save a document raises `NotImplementedError: Use pikepdf.Pdf.pages interface to copy pages from one PDF to another.`

To Reproduce
------------
option A:
- open an existing doc
- modify, or leave as-is
- save or save as (dialog opens either way)

option B:
- start pdfarranger with blank document
- add at least one page
- save or save as

Expected behavior
-----------------
when using "save", if the current doc already has a name, simply save (don't show dialog)

either case, save the document. don't raise an exception

I've used pdfarranger many times before on this system without this issue. I upgraded all my packages yesterday and now I face this.

Backtrace
-------------------
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 976, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 160, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 1050, in save
    exporter.export(self.pdfqueue, to_export, file_out, mode, m)
  File "/usr/lib/python3.10/site-packages/pdfarranger/exporter.py", line 177, in export
    new_page = pdf_output.copy_foreign(current_page)
NotImplementedError: Use pikepdf.Pdf.pages interface to copy pages from one PDF to another.
```

System and Versions
-------------------
PDF Arranger-1.8.2
pikepdf-6.2.1
libqpdf-11.1.1
OS: Gentoo 2.9

**Comment by dreua** [comment]
Is this a flatpak vor regular installiert?

**Comment by dreua** [comment]
Duplicate of #716. Your distro upgraded pikepdf and qpdf to incompatible versions, you will need PDF Arranger 1.9.1 or higher. Please inform the Gentoo Maintainers of thesein order to solve this for all Gentoo users, thanks!

**Comment by petaflot** [comment]
this totally fixed the main issue
