### ISSUE TITLE
Pillow version mismatch

### ISSUE THREAD

**Issue by jorge1b3** [pdfarranger/pdfarranger#866]
Describe the bug
----------------
The flatpak version throw next error, "ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.5.0
Pillow version: 9.2.0
"

To Reproduce
------------

1.  Open the app

Expected behavior
-----------------
The app start

Input files
-----------
```
/app/lib/python3.10/site-packages/PIL/Image.py:125: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.5.0
Pillow version: 9.2.0
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "/app/bin/pdfarranger", line 5, in <module>
    from pdfarranger.pdfarranger import main
  File "/app/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 30, in <module>
    import pikepdf
  File "/app/lib/python3.10/site-packages/pikepdf/__init__.py", line 56, in <module>
    from .models import (
  File "/app/lib/python3.10/site-packages/pikepdf/models/__init__.py", line 16, in <module>
    from .image import PdfImage, PdfInlineImage, UnsupportedImageTypeError
  File "/app/lib/python3.10/site-packages/pikepdf/models/image.py", line 17, in <module>
    from PIL import Image
  File "/app/lib/python3.10/site-packages/PIL/Image.py", line 111, in <module>
    raise ImportError(msg)
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.5.0
Pillow version: 9.2.0
```
System and Versions
-------------------

-   flatpack 1.9.2 version
-   Archlinux

**Comment by dreua** [comment]
Can't reproduce, can you give me the exact version you are using?

```
$ flatpak info com.github.jeromerobert.pdfarranger

PDF Arranger - PDF Merging, Rearranging, Splitting, Rotating and Cropping

          ID: com.github.jeromerobert.pdfarranger
         Ref: app/com.github.jeromerobert.pdfarranger/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.9.2
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 113,9 MB
     Runtime: org.gnome.Platform/x86_64/44
         Sdk: org.gnome.Sdk/x86_64/44

      Commit: af4511536887b018a2578352b8f1b69b8fd37d131f8370afc801cc6fa473da2b
      Parent: 5ce9a4fa5f1b6360bf809712a3fe0b6e723328744a1d2df070ccb35c0eb44d33
     Subject: Update poppler-23.04.0.tar.xz to 23.05.0 (c2192878)
        Date: 2023-05-03 07:39:52 +0000
```

**Comment by dreua** [comment]
I have no idea why this happens for you. This is the same version of the flatpak, it should produce the same results. How exactly are you running PDF Arranger? Any arguments?
