### ISSUE TITLE
Python 3.8 installation instruction

### ISSUE THREAD

**Issue by m-holger** [pdfarranger/pdfarranger#935]
Can you please provide instructions for installing under  Python 3.8. When I try:
```
$ python3.8 -m venv --system-site-packages  v
$ source v/bin/activate
(v) $ pip install --upgrade https://github.com/pdfarranger/pdfarranger/zipball/main
...
Collecting pikepdf>=1.17.0
  Using cached pikepdf-8.2.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
Requirement already satisfied: python-dateutil>=2.4.0 in .../python3.8/site-packages (from pdfarranger==1.10.0) (2.8.1)
Requirement already satisfied: packaging in ... (from pdfarranger==1.10.0) (21.3)
Collecting deprecation
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: Pillow>=9.0 in /usr/lib/python3/dist-packages (from pikepdf>=1.17.0->pdfarranger==1.10.0) (9.0.1)
Collecting lxml>=4.8
  Using cached lxml-4.9.3-cp38-cp38-manylinux_2_28_x86_64.whl (8.0 MB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.4.0->pdfarranger==1.10.0) (1.16.0)
Installing collected packages: lxml, deprecation, pikepdf, pdfarranger
  Attempting uninstall: pdfarranger
    Found existing installation: pdfarranger 1.7.1
    Not uninstalling pdfarranger at .../lib/python3.8/site-packages, outside environment .../v
    Can't uninstall 'pdfarranger'. No files were found to uninstall.
  DEPRECATION: pdfarranger is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pdfarranger ... done
Successfully installed deprecation-2.1.0 lxml-4.9.3 pdfarranger-1.10.0 pikepdf-8.2.3
(v) $ python3 -m pdfarranger
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../v/lib/python3.8/site-packages/pdfarranger/__main__.py", line 2, in <module>
    from pdfarranger import pdfarranger
  File ".../v/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 38, in <module>
    import pikepdf
  File ".../v/lib/python3.8/site-packages/pikepdf/__init__.py", line 53, in <module>
    from .models import (
  File "/.../v/lib/python3.8/site-packages/pikepdf/models/__init__.py", line 16, in <module>
    from .image import PdfImage, PdfInlineImage, UnsupportedImageTypeError
  File ".../v/lib/python3.8/site-packages/pikepdf/models/image.py", line 17, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```
Downgrading pillow I get:
```
(v) $ pip install pillow==8.4.0
...
(v)  python3 -m pdfarranger
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../v/lib/python3.8/site-packages/pdfarranger/__main__.py", line 2, in <module>
    from pdfarranger import pdfarranger
  File ".../v/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 93, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

**Comment by dreua** [comment]
Which version of python comes as default with your distribution? When I tried this on Fedora which comes with Python 3.11, I needed to install `pip install pygobject` because the system does not provide gi for that Python version at all. For you it looks like it falls back to the `/user/lib/python3` directory which may lead to errors if the packages there are not compatible with your venv's Python version.

Could you try creating a venv without the `--system-site-package` flag and install `pip install pygobject` into the venv instead?

**Comment by m-holger** [comment]
> Which version of python comes as default with your distribution

3.10

> Could you try creating a venv without the --system-site-package flag and install pip install pygobject

Fails with:
```
...
Building wheels for collected packages: pycairo
  Building wheel for pycairo (pyproject.toml) ... error
...
      running build_ext
      Package cairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `cairo.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'cairo' found
      Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.

```

**Comment by dreua** [comment]
I do have same packages on my system which probably allowed pycairo to install without issues, I guess it's cairo-devel or cairo-gobject which you'll need. Try installing the corresponding packages of your distribution.

```
$ dnf list installed | grep cairo
cairo.x86_64                                       1.17.8-4.fc38                        @updates                  
cairo-devel.x86_64                                 1.17.8-4.fc38                        @updates                  
cairo-gobject.x86_64                               1.17.8-4.fc38                        @updates                  
cairo-gobject-devel.x86_64                         1.17.8-4.fc38                        @updates                  
cairomm.x86_64                                     1.14.4-7.fc38                        @fedora                   
python2-cairo.x86_64                               1.18.2-13.fc38                       @fedora                   
python3-cairo.x86_64                               1.23.0-2.fc38                        @fedora                   
python3-cairocffi.noarch                           1.3.0-7.fc38                         @fedora                   
python3-cairosvg.noarch                            2.7.0-1.fc38                         @fedora           
```

**Comment by m-holger** [comment]
sorted. It needed `apt install libgirepository1.0-dev`.
